version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7
    steps:
      - run:
          name: Install dependencies
          working_directory: ~/tmp
          command: |
            sudo apt install python-pip python-dev
            sudo pip install awscli --upgrade --user
      - checkout
      - run: npm install
      - run: npm run build
      - deploy:
          name: Deploy to S3
          command: aws s3 sync build/ s3://crypto-trading --region eu-central-1
