version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - deploy:
          name: Deploy to S3
          command: aws s3 sync build/ s3://crypto-trading --region eu-central-1
