version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7
    steps:
      - run:
          name: Install dependencies
          working_directory: ~/tmp
          command: |
            sudo apt-get install awscli
            aws --version
