export default {
publicKey: "-----BEGIN PUBLIC KEY-----\n"+
"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAltKeGnEuE/IJHpzrSpus\n"+
"yt8ZFFFyobcq9D/jotbQSTCG6mtAtve0PK+oQagejy/r74RyiDE0ZQsm7YU7Kdpe\n"+
"MyZN/vsEOWRVdQ2J0ajiGD8OiMSt2PvgHEYHMXB7Q5Dla6tDIeHjLKEK+kE1GLC4\n"+
"Idb/jWvAVKyXTYgpd0Tdd3cyhJ4iBWKgSMjFSxWYdcVMXuayZy8MZkGH9j4tKnYW\n"+
"iWGJ4dqDUfUFA2py0TN/y4V6z3HnbBz0FJwRShYAwPlIGXk3kpupxEN0x/PTU6/r\n"+
"eB6uvZ0hpK383Q/WpxE6Fq2mP5nhTk+Ql1wBwpNutjCEx2B6LiYYTEU9J1Oe5fGb\n"+
"8wIDAQAB\n"+
"-----END PUBLIC KEY-----"
};



